### ISSUE TITLE
django 1.9 prefix

### ISSUE THREAD

**Issue by patryk4815** [elo80ka/django-dynamic-formset#104]
Not work with prefix in django 1.9

https://docs.djangoproject.com/en/1.9/topics/forms/formsets/#using-more-than-one-formset-in-a-view
https://docs.djangoproject.com/en/1.9/ref/forms/api/#prefixes-for-forms

**Comment by patryk4815** [comment]
sry :P   options.prefix

**Comment by elo80ka** [comment]
@patryk4815 no worries :-)
