### ISSUE TITLE
delete checkbox not display 

### ISSUE THREAD

**Issue by dimkoug** [elo80ka/django-dynamic-formset#148]
i have a formset with can_delete=True  but when i render it, it dosen't display the checkbox button 

in html 
      $('.businessextra_formset_row').formset({
        addText: 'ΠΡΟΣΘΗΚΗ ΤΙΜΗΣ',
        deleteText: 'remove',
        prefix: '{{ businessextra_formset.prefix }}'
      });

my formset partial

<table class="table">
  {{ formset.management_form }}
  {% for form in formset.forms %}
    <tr class="{{formset.prefix}}_row">
      {% for field in form.visible_fields %}
      <td class="add">
        {# Include the hidden fields in the form #}
        {% if forloop.first %}
          {% for hidden in form.hidden_fields %}
            {{ hidden }}
          {% endfor %}
        {% endif %}
        {{ field.errors.as_ul }}
        {{ field }}
        {% if form.can_delete %}
          <span>{{ form.DELETE }}</span>
        {% endif %}
      </td>
      {% endfor %}
    </tr>
  {% endfor %}
</table>

**Comment by matthewslaney** [comment]
The checkbox isn't needed. The delete functionality is handled by the "remove" link.

**Comment by dimkoug** [comment]
ok thanks

**Comment by shafay07** [comment]
@dimkoug could you please close the issue?
