### ISSUE TITLE
should copy initial values for hidden fields?

### ISSUE THREAD

**Issue by elo80ka** [elo80ka/django-dynamic-formset#15]
_From [brunog...@gmail.com](https://code.google.com/u/102888874405630962478/) on September 03, 2010 21:05:19_

I have a formset of forms that contains some hidden fields with inital data and i'd like those initial data to be copied when I add a new form using the plugin.

I'm attaching a patch to solve this by not removing the val() on hidden fields, but I think maybe there should be an option for this.

thanks for the plugin, it's really useful :)

bruno gola

_Original issue: http://code.google.com/p/django-dynamic-formset/issues/detail?id=15_

**Comment by thecristen** [comment]
This needs to be added to the documentation! I had the same use case and this fixed my problem.

**Comment by elo80ka** [comment]
Good point...I'll update the documentation.
