### ISSUE TITLE
How would I manipulate a copied row with option "added"

### ISSUE THREAD

**Issue by gevezex** [elo80ka/django-dynamic-formset#175]
I see that there is an option "added" where you can call an action after adding a form. How could I use this option to manipulate a <td> in the row do do some stuff. I would like to know how i could access a field. I tried the variable row but that does not do the trick.

**Comment by cpina** [comment]
If it helps I do:
```
addText: 'add another person',
added: function (row) {
    $(row).find(".invalid-feedback").remove();
}
```

An example (this is for one of the projects, to get inspired but it's not intended to work in a generic way):
https://github.com/Swiss-Polar-Institute/project-application/blob/master/ProjectApplication/project_core/templates/common/_dynamic_formset.tmpl

**Comment by gevezex** [comment]
Ooh wow that was very helpful. Thank your very much! I will close this issue now.
