### ISSUE TITLE
django-dynamic-formset is not an installable python package

### ISSUE THREAD

**Issue by elo80ka** [elo80ka/django-dynamic-formset#34]
_From [matt.cal...@gmail.com](https://code.google.com/u/115229409854689656054/) on August 23, 2011 21:32:45_

What steps will reproduce the problem? 1. Run 'pip install -E svn+ http://django-dynamic-formset.googlecode.com/svn/trunk' What is the expected output? What do you see instead? Expected: Package is installed.
Actual: Error because setup.py does not exist. What version of the product are you using? On what operating system? r17 , mac os x Please provide any additional information below. We should add a setup.py file so that django-dynamic-formset can be installed automatically using a pip/virtualenv solution.

_Original issue: http://code.google.com/p/django-dynamic-formset/issues/detail?id=34_

**Comment by DevanshSoni** [comment]
I have installed django_dynamic_formsets but it says the module not installed dynamic_formsets.
I'm using windows 10 with python version 3.8.5
![image](https://user-images.githubusercontent.com/42613455/93012488-84461c00-f5be-11ea-9080-17d07d71ffbb.png)
