### ISSUE TITLE
adding tags for the repo

### ISSUE THREAD

**Issue by Amomo** [elo80ka/django-dynamic-formset#91]
Hello, 

Adding tags for repo could specify points in history and mark release points.
It's helpful for user to know the version and status of repository, and would enable wider distribution of the library, for example it could be hosted by [cdnjs](https://github.com/cdnjs/cdnjs) ([website](https://cdnjs.com/))

Would you please consider on using tags?
Thanks for your great work!

**Comment by elo80ka** [comment]
Done :-)

**Comment by Amomo** [comment]
Thank you~ :-D
